// These styles apply to every route in the application
import './globals.css';

import Header from '../components/Header';

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<Header></Header>
			<body>{children}</body>
		</html>
	);
}
